export enum ActionType {
    // user scripts
    FETCH_USER_SCRIPTS = "FETCH_USER_SCRIPTS",
    FETCH_ALL_SCRIPTS = "FETCH_ALL_SCRIPTS",
    NEW_SCRIPT = "NEW_SCRIPT",
    REMOVE_SCRIPT = "REMOVE_SCRIPT",
    SET_SCRIPTS_LOADING = "SET_SCRIPTS_LOADING",

    // scripts creation queue
    CLEAN_WORKBENCH = "CLEAN_WORKBENCH",
    ADD_TO_WORKBENCH = "ADD_TO_WORKBENCH",

    // wallet
    WALLET_UPDATE = "WALLET_UPDATE",
    AUTH_CHECK = "AUTH_CHECK",

    // gas tank
    GAS_TANK_BALANCE = "GAS_TANK_BALANCE",
    GAS_TANK_CLAIMABLE = "GAS_TANK_CLAIMABLE",

    // staking
    STAKING_BALANCE = "STAKING_BALANCE",
    STAKING_CLAIMABLE = "STAKING_CLAIMABLE",

    // tokens
    FETCH_TOKENS = "FETCH_TOKENS",

    // history
    FETCH_TRANSACTIONS = "FETCH_TRANSACTIONS",
    UPDATE_TRANSACTION = "UPDATE_TRANSACTION",
    SET_TRANSACTIONS_LOADING = "SET_TRANSACTIONS_LOADING"
}
